services:
  # Backend Service
  - type: web
    name: ecommerce-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate && npm run build
    startCommand: cd backend && npx prisma db push && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # We will set this manually in the Render dashboard for Supabase
      - key: JWT_SECRET
        generateValue: true
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false
      - key: ENCRYPTION_KEY
        value: ecommerce_admin_panel_master_encryption_key_32_chars
      - key: EMAIL_PROVIDER
        value: resend
      - key: EMAIL_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: OrderNest <onboarding@resend.dev>
      - key: ALLOWED_ORIGINS
        value: https://ecommerce-frontend-3m02.onrender.com

  # Frontend Service
  - type: web
    name: ecommerce-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://ecommerce-backend-zlm4.onrender.com/api/v1

databases:
  - name: ecommerce-db
    plan: free
